### ISSUE TITLE
Failure to update on Windows 10 Insider build

### ISSUE THREAD

**Issue by jonthysell** [jonthysell/Mzinga#71]
Looks like some security setting changed in .NET, only repros on WI builds of Windows.

Solution: https://stackoverflow.com/questions/13854068/dtd-prohibited-in-xml-document-exception

Exception details: Mzinga.Viewer.UpdateException: Unable to update Mzinga at this time. ---> System.Xml.XmlException: For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
   at System.Xml.XmlTextReaderImpl.ParseDoctypeDecl()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at Mzinga.Viewer.UpdateUtils.GetLatestInstallerInfos()
   at Mzinga.Viewer.UpdateUtils.UpdateCheck(Boolean confirmUpdate, Boolean showUpToDate)
   --- End of inner exception stack trace ---

**Comment by jonthysell** [comment]
The issue is in the DNS, as it redirects through goo.gl, which some firewalls don't like.
